### ISSUE TITLE
Translation synchronization with English

### ISSUE THREAD

**Issue by AgelxNash** [evolution-cms/evolution#853]
I think, the translations that nobody synchronization we should be deleted.

- [ ] **[Russian](https://github.com/evolution-cms/evolution/issues/868) missing 2 lexicons**
- [ ] **[Italian](https://github.com/evolution-cms/evolution/issues/861) missing 2 lexicons**
- [ ] **[Spanish](https://github.com/evolution-cms/evolution/issues/869) missing 2 lexicons**
- [ ] **[Polish](https://github.com/evolution-cms/evolution/issues/866) missing 3 lexicons + 25 errormsg**
- [ ] **[German](https://github.com/evolution-cms/evolution/issues/859) missing 8 manager lexicons + 2 installer**
- [ ] **[Nederlands](https://github.com/evolution-cms/evolution/issues/863) missing 36 manager lexicons**
- [ ] [Bulgarian](https://github.com/evolution-cms/evolution/issues/854) missing 215 manager lexicons + 25 errormsg + 5 installer
- [ ] [Chinese](https://github.com/evolution-cms/evolution/issues/871) missing 215 manager lexicons + 25 errormsg
- [ ] [Czech](https://github.com/evolution-cms/evolution/issues/855) missing 215 manager lexicons + 25 errormsg + 5 installer
- [ ] [Danish](https://github.com/evolution-cms/evolution/issues/856) missing 215 manager lexicons + 25 errormsg + 5 installer
- [ ] [Finnish](https://github.com/evolution-cms/evolution/issues/857) missing 215 manager lexicons + 25 errormsg + 5 installer
- [ ] [Francais](https://github.com/evolution-cms/evolution/issues/858) missing 215 manager lexicons + 25 errormsg + 5 installer
- [ ] [Hebrew](https://github.com/evolution-cms/evolution/issues/860) missing 215 manager lexicons + 25 errormsg + 5 installer
- [ ] [Norsk](https://github.com/evolution-cms/evolution/issues/864) missing 215 lexicons + 25 errormsg
- [ ] [Persian](https://github.com/evolution-cms/evolution/issues/865) missing 215 manager lexicons + 25 errormsg + 5 installer
- [ ] [Portuguese](https://github.com/evolution-cms/evolution/issues/867) missing 215 manager lexicons + 25 errormsg + 5 installer
- [ ] [Svenska](https://github.com/evolution-cms/evolution/issues/870) missing 215 manager lexicons + 5 installer
- [ ] [Japanese](https://github.com/evolution-cms/evolution/issues/862) missing 216 manager lexicons + 3 installer

Translations checks via script
```php
<?php
$paths = [
    'manager/includes/lang/',
    'install/lang/',
    'manager/includes/lang/errormsg/'
];
$lang = 'russian-UTF8';


foreach ($paths as $path) {
    print $path . PHP_EOL;
    $main = $path . 'english.inc.php';

    include_once $main;
    $mainLang = array_keys($_lang);
    unset($_lang);

    $new = array();

    $files = glob($path . $lang . '.inc.php');

    if (empty($files)) {
        print "\t" . 'File not found: ' . $path . $lang . '.inc.php' . PHP_EOL;
    } else {
        foreach ($files as $file) {
            if ($file !== $main) {
                if (stripos(php_strip_whitespace($file), 'eval(\'?>\' . $contents);') !== false) {
                    continue;
                }
                include_once $file;
                $new[] = array_diff(array_keys($_lang), $mainLang);
                $notTranslate = array_diff($mainLang, array_keys($_lang));
                if (!empty($notTranslate)) {
                    $name = basename($file, '.inc.php');
                    print "\t" . $name . ' => ' . count($notTranslate) . PHP_EOL . implode(
                            PHP_EOL,
                            array_map(function ($val) {
                                return "\t\t" . $val;
                            }, $notTranslate)
                        ) . PHP_EOL;
                }
                unset($_lang, $notTranslate);
            }
        }
    }
    $new = array_unique(array_reduce($new, function ($acc, $item) {
        return array_merge($acc, is_array($item) ? $item : [$item]);
    }, []));

    if (!empty($new)) {
        print_r($new);
    }
    unset($mainLang, $new, $files);
}
```

**Comment by Nicola1971** [comment]
have we abandoned transifex?

**Comment by Nicola1971** [comment]
Note: on transfex, some language are more up to date than on github (just 8 missing strings for the italian language).
![screenshot-www transifex com-2018 11 02-19-48-14](https://user-images.githubusercontent.com/7342798/47934884-ef117100-ded8-11e8-87b0-0845f3446581.png)

I have updated Italian Language for missing strings and pulled

**Comment by Nicola1971** [comment]
For https://github.com/evolution-cms/evolution/issues/859 
German from transifex + https://github.com/evolution-cms/evolution/commit/e5da5675ce0687d2b11c3a4d9052381f312c777e

Missing only 6 strings

@Deesen 

[german.inc.zip](https://github.com/evolution-cms/evolution/files/2543820/german.inc.zip)

**Comment by AgelxNash** [comment]
I also think that files with recoding should be deleted. UTF-8 should be standard

**Comment by elcreator** [comment]
See https://github.com/evolution-cms/evolution/pull/2156
